### ISSUE TITLE
fail to run test against milvus 2.2.11

### ISSUE THREAD

**Issue by yanliang567** [zilliztech/VectorDBBench#166]
my milvus tag: 2.2.0-20230625-41d6ed64
```
File "/usr/local/lib/python3.11/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/usr/local/lib/python3.11/dist-packages/vectordb_bench/frontend/pages/run_test.py", line 65, in <module>
    main()
File "/usr/local/lib/python3.11/dist-packages/vectordb_bench/frontend/pages/run_test.py", line 55, in main
    submitTask(submitContainer, tasks, isAllValid)
File "/usr/local/lib/python3.11/dist-packages/vectordb_bench/frontend/components/run_test/submitTask.py", line 25, in submitTask
    controlPanel(controlPanelContainer, tasks, taskLabel, isAllValid)
File "/usr/local/lib/python3.11/dist-packages/vectordb_bench/frontend/components/run_test/submitTask.py", line 38, in controlPanel
    isRunning = benchMarkRunner.has_running()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/vectordb_bench/interface.py", line 91, in has_running
    self._try_get_signal()
File "/usr/local/lib/python3.11/dist-packages/vectordb_bench/interface.py", line 73, in _try_get_signal
    sig, received = self.receive_conn.recv()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/multiprocessing/connection.py", line 249, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
File "/usr/lib/python3.11/multiprocessing/connection.py", line 382, in _recv
    raise EOFError
```

**Comment by XuanYang-cn** [comment]
@yanliang567 what's the logs above this exception? This exception occurs only when the benchmark process exits unexpectedly

**Comment by yanliang567** [comment]
logs from the clinet:
2023-06-26 04:32:44,050 | INFO: s3 files: dict_keys(['assets.zilliz.com/benchmark/cohere_medium_1m/neighbors.parquet', 'assets.zilliz.com/benchmark/cohere_medium_1m/neighbors_head_1p.parquet', 'assets.zilliz.com/benchmark/cohere_medium_1m/neighbors_tail_1p.parquet', 'assets.zilliz.com/benchmark/cohere_medium_1m/shuffle_train.parquet', 'assets.zilliz.com/benchmark/cohere_medium_1m/test.parquet']) (dataset.py:198) (10636)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.04s/it]
0it [00:00, ?it/s]
2023-06-26 04:32:49,283 | INFO: reading file into memory: /tmp/vectordb_bench/dataset/cohere/cohere_medium_1m/test.parquet (dataset.py:300) (10636)
2023-06-26 04:32:49,329 | INFO: Milvus create collection: VectorDBBenchCollection (milvus.py:53) (10636)
2023-06-26 04:32:49,530 | INFO: reading file into memory: /tmp/vectordb_bench/dataset/cohere/cohere_medium_1m/shuffle_train.parquet (dataset.py:300) (10636)
2023-06-26 04:32:56.673 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/usr/local/lib/python3.11/dist-packages/vectordb_bench/frontend/pages/run_test.py", line 65, in <module>
    main()
  File "/usr/local/lib/python3.11/dist-packages/vectordb_bench/frontend/pages/run_test.py", line 55, in main
    submitTask(submitContainer, tasks, isAllValid)
  File "/usr/local/lib/python3.11/dist-packages/vectordb_bench/frontend/components/run_test/submitTask.py", line 25, in submitTask
    controlPanel(controlPanelContainer, tasks, taskLabel, isAllValid)
  File "/usr/local/lib/python3.11/dist-packages/vectordb_bench/frontend/components/run_test/submitTask.py", line 38, in controlPanel
    isRunning = benchMarkRunner.has_running()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/vectordb_bench/interface.py", line 91, in has_running
    self._try_get_signal()
  File "/usr/local/lib/python3.11/dist-packages/vectordb_bench/interface.py", line 73, in _try_get_signal
    sig, received = self.receive_conn.recv()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 249, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 382, in _recv
    raise EOFError
EOFError

**Comment by XuanYang-cn** [comment]
@yanliang567 memory insufficient, need 16G peak at least

**Comment by liliu-z** [comment]
> @yanliang567 memory insufficient, need at least 16G peek to read file into mem.

Can we do batch file reading to avoid full dataset loading in the future?

**Comment by XuanYang-cn** [comment]
> Can we do batch file reading to avoid full dataset loading in the future?

good idea
