### ISSUE TITLE
No such file or directory: 'streamlit' when strat up VectorDBBench

### ISSUE THREAD

**Issue by become-nice** [zilliztech/VectorDBBench#172]
According to the following command execution, an error occurred.
```shell
pip3 install vectordb-bench
init_bench

2023-06-30 18:01:55,997 | INFO: all configs: [('CASE_TIMEOUT_IN_SECOND', 86400), ('DATASET_LOCAL_DIR', PosixPath('/tmp/vectordb_bench/dataset')), ('DEFAULT_DATASET_URL', 'assets.zilliz.com/benchmark/'), ('DROP_OLD', True), ('LOG_LEVEL', 'INFO'), ('NUM_PER_BATCH', 5000), ('RESULTS_LOCAL_DIR', PosixPath('/usr/local/python3/lib/python3.11/site-packages/vectordb_bench/results')), ('USE_SHUFFLED_DATA', True)] (__main__.py:11) (2367230)
2023-06-30 18:01:55,999 | WARNING: exit, err=[Errno 2] No such file or directory: 'streamlit'
stack trace=Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.11/site-packages/vectordb_bench/__main__.py", line 31, in run_streamlit
    subprocess.run(cmd, check=True)
  File "/usr/local/python3/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/python3/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'streamlit'
```

**Comment by become-nice** [comment]
I have solve this problem. The environment variable is not configured,  streamlit  cannot be found
