### ISSUE TITLE
 ERROR: Failed building wheel for pypika running pip3 install vectordb-bench

### ISSUE THREAD

**Issue by pauldintel** [zilliztech/VectorDBBench#224]
I can't get any help to resolve this while trying both : 

pip3 install vectordb-bench
pip install vectordb-bench

 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pypika
Failed to build pypika
ERROR: Could not build wheels for pypika, which is required to install pyproject.toml-based projects

my python3 version is : 
Python 3.11.5

**Comment by pauldintel** [comment]
here is the full error :

Building wheels for collected packages: pypika
  Building wheel for pypika (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pypika (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/pypika
      copying pypika/enums.py -> build/lib/pypika
      copying pypika/queries.py -> build/lib/pypika
      copying pypika/utils.py -> build/lib/pypika
      copying pypika/functions.py -> build/lib/pypika
      copying pypika/pseudocolumns.py -> build/lib/pypika
      copying pypika/dialects.py -> build/lib/pypika
      copying pypika/analytics.py -> build/lib/pypika
      copying pypika/__init__.py -> build/lib/pypika
      copying pypika/terms.py -> build/lib/pypika
      creating build/lib/pypika/clickhouse
      copying pypika/clickhouse/nullable_arg.py -> build/lib/pypika/clickhouse
      copying pypika/clickhouse/type_conversion.py -> build/lib/pypika/clickhouse
      copying pypika/clickhouse/search_string.py -> build/lib/pypika/clickhouse
      copying pypika/clickhouse/__init__.py -> build/lib/pypika/clickhouse
      copying pypika/clickhouse/array.py -> build/lib/pypika/clickhouse
      copying pypika/clickhouse/dates_and_times.py -> build/lib/pypika/clickhouse
      copying pypika/clickhouse/condition.py -> build/lib/pypika/clickhouse
      running egg_info
      warning: no files found matching 'requirements.txt'
      writing manifest file 'PyPika.egg-info/SOURCES.txt'
      running install
      running install_lib
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 268, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 33, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 622, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 985, in run_command
          cmd_obj.ensure_finalized()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 290, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout. Did you mean: 'install_platlib'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pypika
Failed to build pypika
ERROR: Could not build wheels for pypika, which is required to install pyproject.toml-based projects

**Comment by pauldintel** [comment]
Also it seem with python 3.10.12 no isssue with pypika however 3.11 has issue and until I have 3.11 I can't proceed with pip install vectordb-bench

ubuntu@ip-172-31-1-187:~$ pip install vectordb-bench
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement vectordb-bench (from versions: none)
ERROR: No matching distribution found for vectordb-bench


ubuntu@ip-172-31-1-187:~/ann-benchmarks$ python3 -V
Python 3.10.12
ubuntu@ip-172-31-1-187:~/ann-benchmarks$ pip install PyPika
Defaulting to user installation because normal site-packages is not writeable
Collecting PyPika
  Downloading PyPika-0.48.9.tar.gz (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 KB 2.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: PyPika
  Building wheel for PyPika (pyproject.toml) ... done
  Created wheel for PyPika: filename=PyPika-0.48.9-py2.py3-none-any.whl size=53738 sha256=ff1cb26b6fb29882d18bf1894abdb2b26c3e21d033d4592cf42901488eeb4f41
  Stored in directory: /home/ubuntu/.cache/pip/wheels/e1/26/51/d0bffb3d2fd82256676d7ad3003faea3bd6dddc9577af665f4
Successfully built PyPika
Installing collected packages: PyPika
Successfully installed PyPika-0.48.9
ubuntu@ip-172-31-1-187:~/ann-benchmarks$ cd ..
ubuntu@ip-172-31-1-187:~$
ubuntu@ip-172-31-1-187:~$

**Comment by XuanYang-cn** [comment]
@pauldintel `pypika` is a dependency of chromadb, we could ignore chromadb when install vectordb-bench. It's not released yet, but you could try the following to get the latest vectordb-bench with only pymilvus

```shell
pip install git+https://github.com/zilliztech/vectordbbench.git@main // or
pip install git+ssh://github.com/zilliztech/vectordbbench.git@main
```

**Comment by pauldintel** [comment]
thanks @XuanYang-cn  I managed to get rid of this issue using Python virtualenv .. not sure what was the issue but raised with pypika community too . they are looking at it .

**Comment by LeiW000** [comment]
On my system, the issue can be fixed with "pip3 install --upgrade pip setuptools wheel".
