### ISSUE TITLE
Error executing init_bench

### ISSUE THREAD

**Issue by huelsgp27** [zilliztech/VectorDBBench#233]
```bash
$ init_bench 
2023-10-30 11:19:20,417 | INFO: all configs: [('DATASET_LOCAL_DIR', PosixPath('/tmp/vectordb_bench/dataset')), ('DEFAULT_DATASET_URL', 'assets.zilliz.com/benchmark/'), ('DROP_OLD', True), ('LOG_LEVEL', 'INFO'), ('NUM_PER_BATCH', 5000), ('RESULTS_LOCAL_DIR', PosixPath('/home/ubuntu/.local/lib/python3.11/site-packages/vectordb_bench/results')), ('USE_SHUFFLED_DATA', True)] (__main__.py:11) (38266)

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.


  You can now view your Streamlit app in your browser.

  Network URL: http://10.0.0.13:8501
  External URL: http://43.134.112.49:8501

<frozen importlib._bootstrap>:1047: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1047: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
2023-10-30 11:19:27.711 Uncaught app exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/ubuntu/.local/lib/python3.11/site-packages/vectordb_bench/frontend/vdb_benchmark.py", line 3, in <module>
    from vectordb_bench.frontend.components.check_results.stPageConfig import initResultsPageConfig
  File "/home/ubuntu/.local/lib/python3.11/site-packages/vectordb_bench/frontend/components/check_results/stPageConfig.py", line 1, in <module>
    from vectordb_bench.frontend.const.styles import *
  File "/home/ubuntu/.local/lib/python3.11/site-packages/vectordb_bench/frontend/const/styles.py", line 1, in <module>
    from vectordb_bench.models import DB
  File "/home/ubuntu/.local/lib/python3.11/site-packages/vectordb_bench/models.py", line 15, in <module>
    from .backend.cases import CaseType
  File "/home/ubuntu/.local/lib/python3.11/site-packages/vectordb_bench/backend/cases.py", line 8, in <module>
    from .dataset import Dataset, DatasetManager
  File "/home/ubuntu/.local/lib/python3.11/site-packages/vectordb_bench/backend/dataset.py", line 12, in <module>
    import s3fs
  File "/home/ubuntu/.local/lib/python3.11/site-packages/s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "/home/ubuntu/.local/lib/python3.11/site-packages/s3fs/core.py", line 14, in <module>
    import fsspec  # noqa: F401
    ^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.11/site-packages/fsspec/__init__.py", line 69, in <module>
    process_entries()
  File "/home/ubuntu/.local/lib/python3.11/site-packages/fsspec/__init__.py", line 43, in process_entries
    eps = entry_points()
          ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1040, in entry_points
    return SelectableGroups.load(eps).select(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 476, in load
    ordered = sorted(eps, key=by_group)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1037, in <genexpr>
    eps = itertools.chain.from_iterable(
                                       ^
  File "/usr/lib/python3.11/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
        ^^^^^^^^^^^^
AttributeError: 'PathDistribution' object has no attribute '_normalized_name'
```

**Comment by liliu-z** [comment]
Can I ask your python version?
