### ISSUE TITLE
OpenAI-LARGE-5M test，A process in the process pool was terminated abruptly while the future was running or pending.

### ISSUE THREAD

**Issue by dushulin** [zilliztech/VectorDBBench#249]
2023-12-04 16:59:13,761 | INFO | DB             | CaseType     Dataset               Filter | task_label (task_runner.py:285)
2023-12-04 16:59:13,761 | INFO | -----------    | ------------ -------------------- ------- | -------    (task_runner.py:285)
2023-12-04 16:59:13,761 | INFO | Milvus         | Performance  OpenAI-LARGE-5M         None | 2023120416 (task_runner.py:285)
![image](https://github.com/zilliztech/VectorDBBench/assets/25276301/a95c8e1e-ab9e-4bb7-85ff-c01819dab216)
I use milvus 2.3.2, Whether the tool supports this version？

**Comment by dushulin** [comment]
> This error occurs when starting to insert data. It looks like the downloaded dataset is not being read correctly.
> 
> I would like to check with you how you installed vectordb-bench. if it was installed via git clone, please find this file (vectordb_bench/__init__.py) and change the parameters (LOG_LEVEL) to "DEBUG" to get a more detailed report.
> 
> https://github.com/zilliztech/VectorDBBench/blob/164cc117f1ba9f47b0feab90596d7cfae3a3bf35/vectordb_bench/__init__.py#L10-L12

I download tools by pip, debug info:
2023-12-04 19:05:07,941 | DEBUG: tasks: [TaskConfig(db=<DB.Milvus: 'Milvus'>, db_config=MilvusConfig(db_label='', uri=SecretStr('**********')), db_case_config=IVFFlatConfig(index=<IndexType.IVFFlat: 'IVF_FLAT'>, metric_type=None, nlist=4096, nprobe=10), case_config=CaseConfig(case_id=<CaseType.Performance1536D5M: 11>, custom_case={}))] (interface.py:52) (76221)
2023-12-04 19:05:07,941 | INFO: generated uuid for the tasks: c75ee432eb0c4d56b94cef3f1128dbf8 (interface.py:56) (76221)
2023-12-04 19:05:07,942 | INFO | DB             | CaseType     Dataset               Filter | task_label (task_runner.py:285)
2023-12-04 19:05:07,943 | INFO | -----------    | ------------ -------------------- ------- | -------    (task_runner.py:285)
2023-12-04 19:05:07,943 | INFO | Milvus         | Performance  OpenAI-LARGE-5M         None | 2023120419 (task_runner.py:285)
2023-12-04 19:05:07,943 | INFO: task submitted: id=c75ee432eb0c4d56b94cef3f1128dbf8, 2023120419, case number: 1 (interface.py:211) (76221)
2023-12-04 19:05:11,223 | INFO: [1/1] start case: {'label': <CaseLabel.Performance: 2>, 'dataset': {'data': {'name': 'OpenAI', 'size': 5000000, 'dim': 1536, 'metric_type': <MetricType.COSINE: 'COSINE'>, 'use_shuffled': True, '_size_label': {50000: 'SMALL', 500000: 'MEDIUM', 5000000: 'LARGE'}}}, 'db': 'Milvus'}, drop_old=True (interface.py:143) (76253)
2023-12-04 19:05:12,284 | INFO: local files: ['test.parquet', 'shuffle_train-04-of-10.parquet', 'shuffle_train-02-of-10.parquet', 'shuffle_train-01-of-10.parquet', 'shuffle_train-06-of-10.parquet', 'shuffle_train-05-of-10.parquet', 'shuffle_train-03-of-10.parquet', 'neighbors.parquet', 'shuffle_train-08-of-10.parquet', 'neighbors_head_1p.parquet', 'shuffle_train-07-of-10.parquet', 'shuffle_train-00-of-10.parquet', 'shuffle_train-09-of-10.parquet', 'neighbors_tail_1p.parquet'] (dataset.py:177) (76253)
2023-12-04 19:05:12,284 | INFO: s3 files: dict_keys(['assets.zilliz.com/benchmark/openai_large_5m/neighbors.parquet', 'assets.zilliz.com/benchmark/openai_large_5m/neighbors_head_1p.parquet', 'assets.zilliz.com/benchmark/openai_large_5m/neighbors_tail_1p.parquet', 'assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-00-of-10.parquet', 'assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-01-of-10.parquet', 'assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-02-of-10.parquet', 'assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-03-of-10.parquet', 'assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-04-of-10.parquet', 'assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-05-of-10.parquet', 'assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-06-of-10.parquet', 'assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-07-of-10.parquet', 'assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-08-of-10.parquet', 'assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-09-of-10.parquet', 'assets.zilliz.com/benchmark/openai_large_5m/test.parquet']) (dataset.py:178) (76253)
  0%|                                                                                                                                                                                      | 0/14 [00:00<?, ?it/s]2023-12-04 19:05:12,285 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/neighbors.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/neighbors.parquet (dataset.py:189) (76253)
2023-12-04 19:05:12,312 | DEBUG: calculated local etag 072e4fa27dcb4c116485367d06c6f1a4, expected etag: 072e4fa27dcb4c116485367d06c6f1a4 (dataset.py:224) (76253)
2023-12-04 19:05:12,312 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/neighbors_head_1p.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/neighbors_head_1p.parquet (dataset.py:189) (76253)
2023-12-04 19:05:12,330 | DEBUG: calculated local etag b6ce30e640b35492520f4d161edfe24f, expected etag: b6ce30e640b35492520f4d161edfe24f (dataset.py:224) (76253)
2023-12-04 19:05:12,330 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/neighbors_tail_1p.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/neighbors_tail_1p.parquet (dataset.py:189) (76253)
2023-12-04 19:05:12,342 | DEBUG: calculated local etag 6b1b44cc424ed02c5061afd457d7a04e, expected etag: 6b1b44cc424ed02c5061afd457d7a04e (dataset.py:224) (76253)
2023-12-04 19:05:12,342 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-00-of-10.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/shuffle_train-00-of-10.parquet (dataset.py:189) (76253)
2023-12-04 19:05:30,088 | DEBUG: calculated local etag bf6af323a5e09859e85305400dd6454e-536, expected etag: bf6af323a5e09859e85305400dd6454e-536 (dataset.py:236) (76253)
 29%|█████████████████████████████████████████████████▋                                                                                                                            | 4/14 [00:17<00:44,  4.45s/it]2023-12-04 19:05:30,090 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-01-of-10.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/shuffle_train-01-of-10.parquet (dataset.py:189) (76253)
2023-12-04 19:05:48,127 | DEBUG: calculated local etag 3c61c48a6770abdb4b1a4a47e2efacd5-536, expected etag: 3c61c48a6770abdb4b1a4a47e2efacd5-536 (dataset.py:236) (76253)
 36%|██████████████████████████████████████████████████████████████▏                                                                                                               | 5/14 [00:35<01:12,  8.03s/it]2023-12-04 19:05:48,128 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-02-of-10.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/shuffle_train-02-of-10.parquet (dataset.py:189) (76253)
2023-12-04 19:06:06,092 | DEBUG: calculated local etag 76bf97eb929eeb3ac1e91d4363bfef9c-536, expected etag: 76bf97eb929eeb3ac1e91d4363bfef9c-536 (dataset.py:236) (76253)
 43%|██████████████████████████████████████████████████████████████████████████▌                                                                                                   | 6/14 [00:53<01:25, 10.74s/it]2023-12-04 19:06:06,093 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-03-of-10.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/shuffle_train-03-of-10.parquet (dataset.py:189) (76253)
2023-12-04 19:06:24,047 | DEBUG: calculated local etag 0d49ff652155a2817c16348ed1c31ae8-536, expected etag: 0d49ff652155a2817c16348ed1c31ae8-536 (dataset.py:236) (76253)
 50%|███████████████████████████████████████████████████████████████████████████████████████                                                                                       | 7/14 [01:11<01:29, 12.77s/it]2023-12-04 19:06:24,048 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-04-of-10.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/shuffle_train-04-of-10.parquet (dataset.py:189) (76253)
2023-12-04 19:06:42,009 | DEBUG: calculated local etag 2c5f860210f050c9afb40af1a7a84811-536, expected etag: 2c5f860210f050c9afb40af1a7a84811-536 (dataset.py:236) (76253)
 57%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                          | 8/14 [01:29<01:25, 14.25s/it]
2023-12-04 19:06:42,010 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-05-of-10.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/shuffle_train-05-of-10.parquet (dataset.py:189) (76253)
2023-12-04 19:06:59,997 | DEBUG: calculated local etag 1fcd7f654e5afdebd2eeafd07b4c94c1-536, expected etag: 1fcd7f654e5afdebd2eeafd07b4c94c1-536 (dataset.py:236) (76253)
 64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                              | 9/14 [01:47<01:16, 15.34s/it]2023-12-04 19:06:59,999 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-06-of-10.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/shuffle_train-06-of-10.parquet (dataset.py:189) (76253)
2023-12-04 19:07:18,002 | DEBUG: calculated local etag 2ab20fdb2031ac12cff09f96da46b76e-536, expected etag: 2ab20fdb2031ac12cff09f96da46b76e-536 (dataset.py:236) (76253)
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                 | 10/14 [02:05<01:04, 16.12s/it]2023-12-04 19:07:18,003 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-07-of-10.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/shuffle_train-07-of-10.parquet (dataset.py:189) (76253)
2023-12-04 19:07:35,979 | DEBUG: calculated local etag 378c7d55e3831e050a1dd5d106ff613e-536, expected etag: 378c7d55e3831e050a1dd5d106ff613e-536 (dataset.py:236) (76253)
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                     | 11/14 [02:23<00:50, 16.67s/it]2023-12-04 19:07:35,979 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-08-of-10.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/shuffle_train-08-of-10.parquet (dataset.py:189) (76253)
2023-12-04 19:07:53,960 | DEBUG: calculated local etag 163545f79618a992c17b15d2744f7c64-536, expected etag: 163545f79618a992c17b15d2744f7c64-536 (dataset.py:236) (76253)
 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 12/14 [02:41<00:34, 17.06s/it]2023-12-04 19:07:53,961 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/shuffle_train-09-of-10.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/shuffle_train-09-of-10.parquet (dataset.py:189) (76253)
2023-12-04 19:08:12,079 | DEBUG: calculated local etag 5e1a920822749557de1440bac944704d-536, expected etag: 5e1a920822749557de1440bac944704d-536 (dataset.py:236) (76253)
 93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋            | 13/14 [02:59<00:17, 17.37s/it]2023-12-04 19:08:12,079 | DEBUG: s3 path: assets.zilliz.com/benchmark/openai_large_5m/test.parquet, local_path: /tmp/vectordb_bench/dataset/openai/openai_large_5m/test.parquet (dataset.py:189) (76253)
2023-12-04 19:08:12,109 | DEBUG: calculated local etag 392273730a5f6a8893acca3f4d6d8a9b, expected etag: 392273730a5f6a8893acca3f4d6d8a9b (dataset.py:224) (76253)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [02:59<00:00, 12.84s/it]
0it [00:00, ?it/s]
2023-12-04 19:08:12,111 | DEBUG: OpenAI: available train files ['shuffle_train-00-of-10.parquet', 'shuffle_train-01-of-10.parquet', 'shuffle_train-02-of-10.parquet', 'shuffle_train-03-of-10.parquet', 'shuffle_train-04-of-10.parquet', 'shuffle_train-05-of-10.parquet', 'shuffle_train-06-of-10.parquet', 'shuffle_train-07-of-10.parquet', 'shuffle_train-08-of-10.parquet', 'shuffle_train-09-of-10.parquet'] (dataset.py:257) (76253)
2023-12-04 19:08:12,111 | INFO: Read the entire file into memory: test.parquet (dataset.py:276) (76253)
2023-12-04 19:08:12,470 | INFO: Milvus client drop_old collection: VectorDBBenchCollection (milvus.py:44) (76253)
2023-12-04 19:08:12,475 | INFO: Milvus create collection: VectorDBBenchCollection (milvus.py:54) (76253)
2023-12-04 19:08:16,479 | INFO: (SpawnProcess-1:1) Start inserting embeddings in batch 5000 (serial_runner.py:35) (76356)
2023-12-04 19:08:16,480 | INFO: Get iterator for shuffle_train-00-of-10.parquet (dataset.py:294) (76356)
2023-12-04 19:08:21,980 | WARNING: VectorDB load dataset error: A process in the process pool was terminated abruptly while the future was running or pending. (serial_runner.py:117) (76253)
2023-12-04 19:08:21,991 | WARNING: Failed to run performance case, reason = A process in the process pool was terminated abruptly while the future was running or pending. (task_runner.py:143) (76253)
Traceback (most recent call last):
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 130, in _run_perf_case
    _, load_dur = self._load_train_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/utils.py", line 41, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 157, in _load_train_data
    raise e from None
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 155, in _load_train_data
    runner.run()
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/runner/serial_runner.py", line 149, in run
    count, dur = self._insert_all_batches()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/utils.py", line 41, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/runner/serial_runner.py", line 118, in _insert_all_batches
    raise e from e
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/runner/serial_runner.py", line 109, in _insert_all_batches
    count = future.result(timeout=self.timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
2023-12-04 19:08:22,012 | WARNING: [1/1] case {'label': <CaseLabel.Performance: 2>, 'dataset': {'data': {'name': 'OpenAI', 'size': 5000000, 'dim': 1536, 'metric_type': <MetricType.COSINE: 'COSINE'>, 'use_shuffled': True, '_size_label': {50000: 'SMALL', 500000: 'MEDIUM', 5000000: 'LARGE'}}}, 'db': 'Milvus'} failed to run, reason=A process in the process pool was terminated abruptly while the future was running or pending. (interface.py:163) (76253)
Traceback (most recent call last):
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/interface.py", line 144, in _async_task_v2
    case_res.metrics = runner.run(drop_old)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 98, in run
    return self._run_perf_case(drop_old)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 145, in _run_perf_case
    raise e from None
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 130, in _run_perf_case
    _, load_dur = self._load_train_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/utils.py", line 41, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 157, in _load_train_data
    raise e from None
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 155, in _load_train_data
    runner.run()
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/runner/serial_runner.py", line 149, in run
    count, dur = self._insert_all_batches()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/utils.py", line 41, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/runner/serial_runner.py", line 118, in _insert_all_batches
    raise e from e
  File "/opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/backend/runner/serial_runner.py", line 109, in _insert_all_batches
    count = future.result(timeout=self.timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/milvusbench/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
2023-12-04 19:08:22,020 | INFO |Task summery: run_id=c75ee, task_label=2023120419 (models.py:231)
2023-12-04 19:08:22,020 | INFO |DB     | db_label case               label      | load_dur    qps        latency(p99)    recall        max_load_count | label (models.py:231)
2023-12-04 19:08:22,020 | INFO |------ | -------- ------------------ ---------- | ----------- ---------- --------------- ------------- -------------- | ----- (models.py:231)
2023-12-04 19:08:22,020 | INFO |Milvus |          Performance1536D5M 2023120419 | 0.0         0.0        0.0             0.0           0              | x     (models.py:231)
2023-12-04 19:08:22,021 | INFO: write results to disk /opt/conda/envs/milvusbench/lib/python3.11/site-packages/vectordb_bench/results/Milvus/result_20231204_2023120419_milvus.json (models.py:129) (76253)
2023-12-04 19:08:22,027 | INFO: Succes to finish task: label=2023120419, run_id=c75ee432eb0c4d56b94cef3f1128dbf8 (interface.py:183) (76253)
/opt/conda/envs/milvusbench/lib/python3.11/site-packages/s3fs/core.py:583: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
2023-12-04 19:08:22,270 | DEBUG: Sigal received to process: SIGNAL.WIP, 0 (interface.py:74) (76221)
2023-12-04 19:08:27,552 | DEBUG: Sigal received to process: SIGNAL.SUCCESS, None (interface.py:74) (76221)

**Comment by dushulin** [comment]
BTW, I run this tool in a k8s pod(docker container) which request 8c-30g resources

**Comment by XuanYang-cn** [comment]
@dushulin It failed at reading the first train data, can you see the pod's mem-usage while reading the dataset? Or you could try raise the request memory resources from 30G to 50G?

**Comment by dushulin** [comment]
@XuanYang-cn I run this benchmark after raise mem to 50Gi, but I meet another question, maybe 500w vectors are too large to load in milvus node mem, the milvus cluster resource is below:
rootCoordinator:
  replicas: 2
  activeStandby:
    enabled: true
  resources:
    limits:
      cpu: 1
      memory: 2Gi
indexCoordinator:
  replicas: 2
  activeStandby:
    enabled: true
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
queryCoordinator:
  replicas: 2
  activeStandby:
    enabled: true
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
dataCoordinator:
  replicas: 2
  activeStandby:
    enabled: true
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
proxy:
  replicas: 2
  resources:
    limits:
      cpu: 2
      memory: 8Gi
queryNode:
  replicas: 3
  resources:
    limits:
      cpu: 2
      memory: 12Gi
dataNode:
  replicas: 3
  resources:
    limits:
      cpu: 2
      memory: 16Gi
indexNode:
  replicas: 3
  resources:
    limits:
      cpu: 4
      memory: 16Gi
---
If we want to complete this Benchmark, what is the resource settings you recommend?

**Comment by dushulin** [comment]
btw, I want to know the field explanation which standard benchmark you team gave.
![image](https://github.com/zilliztech/VectorDBBench/assets/25276301/3b08e8ef-3c66-4d90-9e35-2801093cab15)
eg. The explaination of the last field ”disk“

**Comment by alwayslove2013** [comment]
@dushulin `disk` means `DiskAnn`, one of the on-disk index types.

https://milvus.io/docs/disk_index.md

**Comment by XuanYang-cn** [comment]
@dushulin We use 16c64g Milvus-HNSW and 4c16G DiskANN for 5M-1536DIM-OpenAI dataset and 10M-768DIM-Cohere dataset. They are both milvus standalone.

We didn't test for Milvus distributed, I recommand using 1 QueryNode, 1 DataNode. Leave at least 64G mem for querynode if using HNSW index, OR 16G for DiskANN with 50G nvme SSD. Here's a sizing tool to help calculating the resource requirements https://milvus.io/tools/sizing

![image](https://github.com/zilliztech/VectorDBBench/assets/51370125/40248960-f659-4075-8300-84a6bf771017)

**Comment by xiaofan-luan** [comment]
> @XuanYang-cn I run this benchmark after raise mem to 50Gi, but I meet another question, maybe 500w vectors are too large to load in milvus node mem, the milvus cluster resource is below: rootCoordinator: replicas: 2 activeStandby: enabled: true resources: limits: cpu: 1 memory: 2Gi indexCoordinator: replicas: 2 activeStandby: enabled: true resources: limits: cpu: "1" memory: 1Gi queryCoordinator: replicas: 2 activeStandby: enabled: true resources: limits: cpu: "1" memory: 1Gi dataCoordinator: replicas: 2 activeStandby: enabled: true resources: limits: cpu: "1" memory: 1Gi proxy: replicas: 2 resources: limits: cpu: 2 memory: 8Gi queryNode: replicas: 3 resources: limits: cpu: 2 memory: 12Gi dataNode: replicas: 3 resources: limits: cpu: 2 memory: 16Gi indexNode: replicas: 3 resources: limits: cpu: 4 memory: 16Gi
> 
> If we want to complete this Benchmark, what is the resource settings you recommend?

but you should leave at least 3 * 16GB memory for querynode. another 1 * 8GB for indexnode, 1* 8GB for index node. So overall all it could take around 64GB memory to finish 5M 1536dim test

**Comment by XuanYang-cn** [comment]
@dushulin we just used the default index params.

**Comment by XuanYang-cn** [comment]
> Is there any possibility of single -point failure using one query node？
 If this's what you worry about, try use 2 querynode with 8 cpus.

**Comment by dushulin** [comment]
> > Is there any possibility of single -point failure using one query node？
> 
> @dushulin If this's what you worry about, try use 2 querynode with 8 cpus.

The standard test milvus-16c64g-hnsw, use cluster or standalone mode?
BTW, I checked the monitoring of QueryNode, CPU usage is 1.75, what meaning of this metric?I guess query node use 1.75 core cpu resource?
![image](https://github.com/zilliztech/VectorDBBench/assets/25276301/67b45d29-8afb-42da-a918-c9b5a81226e4)

**Comment by alwayslove2013** [comment]
standalone mode. All of the standard test results of milvus used standalone mode.
> The standard test milvus-16c64g-hnsw, use cluster or standalone mode? 

yes, 1.75 means using 1.75 core cpu resources.
> BTW, I checked the monitoring of QueryNode, CPU usage is 1.75, what meaning of this metric?I guess query node use 1.75 core cpu resource?

**Comment by dushulin** [comment]
> standalone mode. All of the standard test results of milvus used standalone mode.
> 
> > The standard test milvus-16c64g-hnsw, use cluster or standalone mode?
> 
> yes, 1.75 means using 1.75 core cpu resources.
> 
> > BTW, I checked the monitoring of QueryNode, CPU usage is 1.75, what meaning of this metric?I guess query node use 1.75 core cpu resource?

I increase the CPU resource of querynode three times(6 cores), and indexnode mem decrease 2Gi for each replicas,and test result is below:
![image](https://github.com/zilliztech/VectorDBBench/assets/25276301/f605b446-4ed9-46b1-b7bc-a964eb9c6f44)
the test result is alse worse than standard test(standalone mode)
BTW, I found cpu usage is 4.x for each querynode replica, I think cpu resource is enough for this benchmark situation.
PS: 
1. I want to know if I increase the queynode replica nums, wheather qps can increase liner. maybe not liner from my test results. (you can see line2 and line3 in picture)
2. When 5 million vectors are loaded into multiple querynode replicas, should each replica load the full amount of vectors or perform fragmented loading?

**Comment by alwayslove2013** [comment]
@dushulin 
It's not unusual that 3\*6c performs worse than 1\*16c. 
The standalone mode is more flexible to get the extreme performance of a single machine. However, the capacity of a single machine is limited. 
The cluster mode is born for super large data scenarios and has high scalability.
> the test result is also worse than standard test(standalone mode)

Considering scheduling and communication, a 2x querynode performance gain would be slightly less than 2x, and not be strictly linear.
> 1. I want to know if I increase the queynode replica nums, whether qps can increase liner. maybe not linear from my test results. (you can see line2 and line3 in picture)

Querynode replicas load different parts of data.
> 2. When 5 million vectors are loaded into multiple querynode replicas, should each replica load the full amount of vectors or perform fragmented loading?
