### ISSUE TITLE
Failing Search Performance Test (100M Dataset, 768 Dim)

### ISSUE THREAD

**Issue by kish5430** [zilliztech/VectorDBBench#286]
HI Team,

Search Performance Test (100M Dataset, 768 Dim) is failing with below error. Could you plz fix the issue asap.

Error:
2024-03-01 04:29:23,424 | INFO: local dataset root path not exist, creating it: /tmp/vectordb_bench/dataset/laion/laion_large_100m (data_source.py:126) (55)
2024-03-01 04:29:23,425 | INFO: Start to downloading files, total count: 104 (data_source.py:142) (55)
  2%|▏         | 2/104 [00:02<01:42,  1.01s/it]
2024-03-01 04:29:25,444 | WARNING: pre run case error: The specified key does not exist. (task_runner.py:92) (55)
2024-03-01 04:29:25,444 | WARNING: [1/1] case {'label': <CaseLabel.Performance: 2>, 'dataset': {'data': {'name': 'LAION', 'size': 100000000, 'dim': 768, 'metric_type': <MetricType.L2: 'L2'>}}, 'db': 'Milvus-100M_HNSW'} failed to run, reason=The specified key does not exist. (interface.py:187) (55)
Traceback (most recent call last):
  File "/app/VectorDBBench/lib64/python3.11/site-packages/vectordb_bench/interface.py", line 168, in _async_task_v2
    case_res.metrics = runner.run(drop_old)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/app/VectorDBBench/lib64/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 96, in run
    self._pre_run(drop_old)
  File "/app/VectorDBBench/lib64/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 93, in _pre_run
    raise e from None
  File "/app/VectorDBBench/lib64/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 87, in _pre_run
    self.ca.dataset.prepare(self.dataset_source)
  File "/app/VectorDBBench/lib64/python3.11/site-packages/vectordb_bench/backend/dataset.py", line 202, in prepare
    source.reader().read(
  File "/app/VectorDBBench/lib64/python3.11/site-packages/vectordb_bench/backend/data_source.py", line 145, in read
    self.fs.download(s3_file, local_ds_root.as_posix())
  File "/app/VectorDBBench/lib64/python3.11/site-packages/fsspec/spec.py", line 1534, in download
    return self.get(rpath, lpath, recursive=recursive, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/VectorDBBench/lib64/python3.11/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/VectorDBBench/lib64/python3.11/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/app/VectorDBBench/lib64/python3.11/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
                ^^^^^^^^^^
  File "/app/VectorDBBench/lib64/python3.11/site-packages/fsspec/asyn.py", line 650, in _get
    return await _run_coros_in_chunks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/VectorDBBench/lib64/python3.11/site-packages/fsspec/asyn.py", line 254, in _run_coros_in_chunks
    await asyncio.gather(*chunk, return_exceptions=return_exceptions),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "/app/VectorDBBench/lib64/python3.11/site-packages/s3fs/core.py", line 1224, in _get_file
    body, content_length = await _open_file(range=0)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/VectorDBBench/lib64/python3.11/site-packages/s3fs/core.py", line 1215, in _open_file
    resp = await self._call_s3(
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/VectorDBBench/lib64/python3.11/site-packages/s3fs/core.py", line 348, in _call_s3
    return await _error_wrapper(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/VectorDBBench/lib64/python3.11/site-packages/s3fs/core.py", line 140, in _error_wrapper
    raise err

Thanks

**Comment by XuanYang-cn** [comment]
same as: #275

**Comment by XuanYang-cn** [comment]
should be fixed by #287 
The fixes will be released at 0.0.7 milestone

**Comment by anrahman4** [comment]
When will 0.0.7 be released as the main branch for git cloning? Also when will this be pushed to pip3?
