### ISSUE TITLE
pgvector HNSW support in v0.0.8

### ISSUE THREAD

**Issue by luckxuqin** [zilliztech/VectorDBBench#309]
Nice to see pgvector HNSW support in 0.0.8 release, but after upgrade this version I got the following error,

```
2024-04-24 08:15:36.786 Uncaught app exception
Traceback (most recent call last):
  File "/home/xmark/.pyenv/versions/3.12.3/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/home/xmark/.pyenv/versions/3.12.3/lib/python3.12/site-packages/vectordb_bench/frontend/pages/run_test.py", line 65, in <module>
    main()
  File "/home/xmark/.pyenv/versions/3.12.3/lib/python3.12/site-packages/vectordb_bench/frontend/pages/run_test.py", line 48, in main
    generate_tasks(activedDbList, dbConfigs, activedCaseList, allCaseConfigs)
  File "/home/xmark/.pyenv/versions/3.12.3/lib/python3.12/site-packages/vectordb_bench/frontend/components/run_test/generateTasks.py", line 15, in generate_tasks
    db_case_config=db.case_config_cls(
                   ^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```
 
Also I don't see how to switch to HNSW index for pgvector in the web console, it defaults to use IVFFLAT, correct?

**Comment by alwayslove2013** [comment]
Fixed.

**Comment by alwayslove2013** [comment]
@luckxuqin Now you can choose `HNSW` or `IVFFlat` in the web ui.
> how to switch to HNSW index for pgvector in the web console
![image](https://github.com/zilliztech/VectorDBBench/assets/22510720/94c93541-da60-48c6-b59e-1be481dffcfe)
