### ISSUE TITLE
Deploy error in V0.0.8

### ISSUE THREAD

**Issue by escblue** [zilliztech/VectorDBBench#310]
version in V0.08 

OS：Red-hat8 /ubuntu22/ win10

error:

ile "C:\Users\appadmin\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
File "C:\Users\appadmin\AppData\Local\Programs\Python\Python311\Lib\site-packages\vectordb_bench\frontend\pages\run_test.py", line 65, in <module>
    main()
File "C:\Users\appadmin\AppData\Local\Programs\Python\Python311\Lib\site-packages\vectordb_bench\frontend\pages\run_test.py", line 48, in main
    generate_tasks(activedDbList, dbConfigs, activedCaseList, allCaseConfigs)
File "C:\Users\appadmin\AppData\Local\Programs\Python\Python311\Lib\site-packages\vectordb_bench\frontend\components\run_test\generateTasks.py", line 15, in generate_tasks
    db_case_config=db.case_config_cls(
                   ^^^^^^^^^^^^^^^^^^^

**Comment by alwayslove2013** [comment]
@escblue we need the detailed log, as well as the test case you have selected.

**Comment by escblue** [comment]
Deploy steps：

pip install vectordb-bench[pgvector]
init_bench

Get error below:
Network URL: http://192.168.3.130:8501

2024-04-25 20:56:50.706 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\li.chen\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\li.chen\AppData\Local\Programs\Python\Python312\Lib\site-packages\vectordb_bench\frontend\vdb_benchmark.py", line 50, in <module>
    main()
  File "C:\Users\li.chen\AppData\Local\Programs\Python\Python312\Lib\site-packages\vectordb_bench\frontend\vdb_benchmark.py", line 20, in main
    allResults = benchMarkRunner.get_results()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\li.chen\AppData\Local\Programs\Python\Python312\Lib\site-packages\vectordb_bench\interface.py", line 89, in get_results
    return ResultCollector.collect(target_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\li.chen\AppData\Local\Programs\Python\Python312\Lib\site-packages\vectordb_bench\backend\result_collector.py", line 19, in collect
    file_result = TestResult.read_file(json_file, trans_unit=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\li.chen\AppData\Local\Programs\Python\Python312\Lib\site-packages\vectordb_bench\models.py", line 164, in read_file
    task_config["db_case_config"] = db.case_config_cls(
                                    ^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable


![image](https://github.com/zilliztech/VectorDBBench/assets/7471658/c7338933-81c4-45f2-b645-0b3e06116894)


Change to 0.0.7 version
pip install vectordb-bench[pgvector]==0.0.7
it works.

**Comment by alwayslove2013** [comment]
PR: #311 Fixed.
