### ISSUE TITLE
Not able to run benchmark on milvus

### ISSUE THREAD

**Issue by badrinath1988** [zilliztech/VectorDBBench#351]
We have installed the standalone milvus in openshift cluster .
we are trying to execute the benchmark on milvus
while executing we are getting the below error

Request to help us to resolve the issue  .

Error: 
(base) [root@csahda ~]# init_bench
2024-07-25 09:42:43,669 | INFO: all configs: [('ALIYUN_OSS_URL', 'assets.zilliz.com.cn/benchmark/'), ('AWS_S3_URL', 'assets.zilliz.com/benchmark/'), ('DATASET_LOCAL_DIR', PosixPath('/tmp/vectordb_bench/dataset')), ('DEFAULT_DATASET_URL', 'assets.zilliz.com/benchmark/'), ('DROP_OLD', True), ('LOG_LEVEL', 'INFO'), ('NUM_CONCURRENCY', [1, 5, 10, 15, 20, 25, 30, 35]), ('NUM_PER_BATCH', 5000), ('RESULTS_LOCAL_DIR', PosixPath('/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/results')), ('USE_SHUFFLED_DATA', True)] (__main__.py:11) (1991739)

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.50.20:8501

2024-07-25 09:45:05,728 | INFO: generated uuid for the tasks: 1eb524a675c8494e99242f5da484be36 (interface.py:69) (1991740)
2024-07-25 09:45:05,787 | INFO | DB             | CaseType     Dataset               Filter | task_label (task_runner.py:288)
2024-07-25 09:45:05,787 | INFO | -----------    | ------------ -------------------- ------- | -------    (task_runner.py:288)
2024-07-25 09:45:05,787 | INFO | Milvus-default | Performance  Cohere-MEDIUM-1M        None | 2024072509 (task_runner.py:288)
2024-07-25 09:45:05,787 | INFO: task submitted: id=1eb524a675c8494e99242f5da484be36, 2024072509, case number: 1 (interface.py:235) (1991740)
2024-07-25 09:45:06,439 | INFO: [1/1] start case: {'label': <CaseLabel.Performance: 2>, 'dataset': {'data': {'name': 'Cohere', 'size': 1000000, 'dim': 768, 'metric_type': <MetricType.COSINE: 'COSINE'>}}, 'db': 'Milvus-default'}, drop_old=True (interface.py:167) (1992218)
2024-07-25 09:45:06,531 | INFO: Milvus create collection: VectorDBBenchCollection (milvus.py:55) (1992218)
RPC error: [create_index], <MilvusException: (code=0, message=metric type not found or not supported, supported: [L2 IP])>, <Time:{'RPC start': '2024-07-25 09:45:06.541340', 'RPC error': '2024-07-25 09:45:06.543566'}>
2024-07-25 09:45:06,543 | WARNING: pre run case error: <MilvusException: (code=0, message=metric type not found or not supported, supported: [L2 IP])> (task_runner.py:92) (1992218)
2024-07-25 09:45:06,543 | WARNING: [1/1] case {'label': <CaseLabel.Performance: 2>, 'dataset': {'data': {'name': 'Cohere', 'size': 1000000, 'dim': 768, 'metric_type': <MetricType.COSINE: 'COSINE'>}}, 'db': 'Milvus-default'} failed to run, reason=<MilvusException: (code=0, message=metric type not found or not supported, supported: [L2 IP])> (interface.py:187) (1992218)
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/interface.py", line 168, in _async_task_v2
    case_res.metrics = runner.run(drop_old)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/backend/task_runner.py", line 96, in run
    self._pre_run(drop_old)
  File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/backend/task_runner.py", line 93, in _pre_run
    raise e from None
  File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/backend/task_runner.py", line 86, in _pre_run
    self.init_db(drop_old)
  File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/backend/task_runner.py", line 77, in init_db
    self.db = db_cls(
              ^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/backend/clients/milvus/milvus.py", line 64, in __init__
    col.create_index(
  File "/root/miniconda3/lib/python3.12/site-packages/pymilvus/orm/collection.py", line 1371, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/pymilvus/decorators.py", line 147, in handler
    raise e from e
  File "/root/miniconda3/lib/python3.12/site-packages/pymilvus/decorators.py", line 143, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/pymilvus/decorators.py", line 182, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/pymilvus/decorators.py", line 122, in handler
    raise e from e
  File "/root/miniconda3/lib/python3.12/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/pymilvus/client/grpc_handler.py", line 987, in create_index
    check_status(status)
  File "/root/miniconda3/lib/python3.12/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=0, message=metric type not found or not supported, supported: [L2 IP])>
2024-07-25 09:45:06,545 | INFO |Task summary: run_id=1eb52, task_label=2024072509 (models.py:289)
2024-07-25 09:45:06,545 | INFO |DB     | db_label   case              label      | load_dur    qps        latency(p99)    recall        max_load_count | label (models.py:289)
2024-07-25 09:45:06,545 | INFO |------ | ---------- ----------------- ---------- | ----------- ---------- --------------- ------------- -------------- | ----- (models.py:289)
2024-07-25 09:45:06,545 | INFO |Milvus | default    Performance768D1M 2024072509 | 0.0         0.0        0.0             0.0           0              | x     (models.py:289)

Output from openshift:

(base) [root@csahda ~]# oc get pods
NAME                                            READY   STATUS    RESTARTS   AGE
my-release-etcd-0                               1/1     Running   0          43h
my-release-milvus-standalone-64bdc89f66-rzxdj   1/1     Running   0          43h
my-release-minio-67c5bcb8d7-m9nvk               1/1     Running   0          43h

-Badrinath

**Comment by badrinath1988** [comment]
thanks , issue got resolved by upgrading the milvus database to 2.4.5 .
