### ISSUE TITLE
not able to run vectordbbench on redis

### ISSUE THREAD

**Issue by badrinath1988** [zilliztech/VectorDBBench#359]
HI team , 

we instlled the redis in kubernet plaform .

while connecting  running the benchmark , we getting the below error 

2024-08-12 16:31:58,339 | INFO: generated uuid for the tasks: 4a759b2b1183406f875710d710ad57d7 (interface.py:69) (1218151)
2024-08-12 16:31:58,339 | INFO | DB             | CaseType     Dataset               Filter | task_label (task_runner.py:288)
2024-08-12 16:31:58,339 | INFO | -----------    | ------------ -------------------- ------- | -------    (task_runner.py:288)
2024-08-12 16:31:58,340 | INFO | Redis-redis-sanjeev1 | Performance  Cohere-MEDIUM-1M        None | 12345678   (task_runner.py:288)
2024-08-12 16:31:58,340 | INFO: task submitted: id=4a759b2b1183406f875710d710ad57d7, 12345678, case number: 1 (interface.py:235) (1218151)
2024-08-12 16:31:58,988 | INFO: [1/1] start case: {'label': <CaseLabel.Performance: 2>, 'dataset': {'data': {'name': 'Cohere', 'size': 1000000, 'dim': 768, 'metric_type': <MetricType.COSINE: 'COSINE'>}}, 'db': 'Redis-redis-sanjeev1'}, drop_old=True (interface.py:167) (2053929)
2024-08-12 16:31:59,031 | INFO: Redis client drop_old collection: index (redis.py:42) (2053929)
2024-08-12 16:31:59,032 | WARNING: pre run case error: unknown command 'FT.CREATE', with args beginning with: 'index' 'ON' 'HASH' 'SCORE' '1.0' 'SCHEMA' 'id' 'TAG' 'SEPARATOR' ',' 'metadata' 'NUMERIC' 'vector' 'VECTOR' 'HNSW' '6' 'TYPE' 'F'  (task_runner.py:92) (2053929)
2024-08-12 16:31:59,032 | WARNING: [1/1] case {'label': <CaseLabel.Performance: 2>, 'dataset': {'data': {'name': 'Cohere', 'size': 1000000, 'dim': 768, 'metric_type': <MetricType.COSINE: 'COSINE'>}}, 'db': 'Redis-redis-sanjeev1'} failed to run, reason=unknown command 'FT.CREATE', with args beginning with: 'index' 'ON' 'HASH' 'SCORE' '1.0' 'SCHEMA' 'id' 'TAG' 'SEPARATOR' ',' 'metadata' 'NUMERIC' 'vector' 'VECTOR' 'HNSW' '6' 'TYPE' 'F'  (interface.py:187) (2053929)
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/interface.py", line 168, in _async_task_v2
    case_res.metrics = runner.run(drop_old)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/backend/task_runner.py", line 96, in run
    self._pre_run(drop_old)
  File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/backend/task_runner.py", line 93, in _pre_run
    raise e from None
  File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/backend/task_runner.py", line 86, in _pre_run
    self.init_db(drop_old)
  File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/backend/task_runner.py", line 77, in init_db
    self.db = db_cls(
              ^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/backend/clients/redis/redis.py", line 44, in __init__
    self.make_index(dim, conn)
  File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/backend/clients/redis/redis.py", line 68, in make_index
    rs.create_index(schema, definition=definition)
  File "/root/miniconda3/lib/python3.12/site-packages/redis/commands/search/commands.py", line 223, in create_index
    return self.execute_command(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/redis/client.py", line 548, in execute_command
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/redis/client.py", line 549, in <lambda>
    lambda: self._send_command_parse_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/redis/client.py", line 525, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/redis/client.py", line 565, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/redis/connection.py", line 536, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'FT.CREATE', with args beginning with: 'index' 'ON' 'HASH' 'SCORE' '1.0' 'SCHEMA' 'id' 'TAG' 'SEPARATOR' ',' 'metadata' 'NUMERIC' 'vector' 'VECTOR' 'HNSW' '6' 'TYPE' 'F'
2024-08-12 16:31:59,033 | INFO |Task summary: run_id=4a759, task_label=12345678 (models.py:289)
2024-08-12 16:31:59,033 | INFO |DB    | db_label          case              label    | load_dur    qps        latency(p99)    recall        max_load_count | label (models.py:289)
2024-08-12 16:31:59,033 | INFO |----- | ----------------- ----------------- -------- | ----------- ---------- --------------- ------------- -------------- | ----- (models.py:289)
2024-08-12 16:31:59,033 | INFO |Redis | redis-sanjeev1    Performance768D1M 12345678 | 0.0         0.0        0.0             0.0           0              | x     (models.py:289)
2024-08-12 16:31:59,033 | INFO: write results to disk /root/miniconda3/lib/python3.12/site-packages/vectordb_bench/results/Redis/result_20240812_12345678_redis.json (models.py:147) (2053929)
2024-08-12 16:31:59,034 | INFO: Succes to finish task: label=12345678, run_id=4a759b2b1183406f875710d710ad57d7 (interface.py:207) (2053929)

**Comment by alwayslove2013** [comment]
@badrinath1988 It seems that `redis` client cannot `create index`. I will check it soon.
 > File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/backend/clients/redis/redis.py", line 44, in init
self.make_index(dim, conn)
File "/root/miniconda3/lib/python3.12/site-packages/vectordb_bench/backend/clients/redis/redis.py", line 68, in make_index
rs.create_index(schema, definition=definition)

> redis.exceptions.ResponseError: unknown command 'FT.CREATE', with args beginning with: 'index' 'ON' 'HASH' 'SCORE' '1.0' 'SCHEMA' 'id' 'TAG' 'SEPARATOR' ',' 'metadata' 'NUMERIC' 'vector' 'VECTOR' 'HNSW' '6' 'TYPE' 'F'
