### ISSUE TITLE
Issue while running VectorDBBench for weavaite

### ISSUE THREAD

**Issue by kilo1234** [zilliztech/VectorDBBench#391]
You can see below from the backtrace that: db_config.update() api is expecting a single argument but we are passing two arguments in code. I am running weaviate on Kubernetes cluster.

2024-10-29 17:41:32,650 | WARNING: pre run case error: update expected at most 1 argument, got 2 (task_runner.py:96) (441579)
2024-10-29 17:41:32,651 | WARNING: [1/1] case {'label': <CaseLabel.Performance: 2>, 'dataset': {'data': {'name': 'LAION', 'size': 100000000, 'dim': 768, 'metric_type': <MetricType.L2: 'L2'>}}, 'db': 'WeaviateCloud'} failed to run, reason=update expected at most 1 argument, got 2 (interface.py:184) (441579)
Traceback (most recent call last):
  File "/home/ubuntu/myvenv/lib/python3.11/site-packages/vectordb_bench/interface.py", line 165, in _async_task_v2
    case_res.metrics = runner.run(drop_old)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myvenv/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 102, in run
    self._pre_run(drop_old)
  File "/home/ubuntu/myvenv/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 97, in _pre_run
    raise e from None
  File "/home/ubuntu/myvenv/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 88, in _pre_run
    self.init_db(drop_old)
  File "/home/ubuntu/myvenv/lib/python3.11/site-packages/vectordb_bench/backend/task_runner.py", line 78, in init_db
    self.db = db_cls(
              ^^^^^^^
  File "/home/ubuntu/myvenv/lib/python3.11/site-packages/vectordb_bench/backend/clients/weaviate_cloud/weaviate_cloud.py", line 26, in __init__
    db_config.update("auth_client_secret", weaviate.AuthApiKey(api_key=db_config.get("auth_client_secret")))
TypeError: update expected at most 1 argument, got 2

**Comment by alwayslove2013** [comment]
@kilo1234 I will check this issue as soon as possible.

**Comment by alwayslove2013** [comment]
@kilo1234 fixed in #392
