### ISSUE TITLE
Failing Search Performance Test

### ISSUE THREAD

**Issue by midonKing** [zilliztech/VectorDBBench#402]
2024-11-06 10:14:12.581 Uncaught app exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py311/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/opt/anaconda3/envs/py311/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/home/axhu/VectorDBBench/vectordb_bench/frontend/vdb_benchmark.py", line 50, in <module>
    main()
  File "/home/axhu/VectorDBBench/vectordb_bench/frontend/vdb_benchmark.py", line 43, in main
    drawCharts(st, shownData, failedTasks, showCases)
  File "/home/axhu/VectorDBBench/vectordb_bench/frontend/components/check_results/charts.py", line 14, in drawCharts
    drawChart(data, chartContainer)
  File "/home/axhu/VectorDBBench/vectordb_bench/frontend/components/check_results/charts.py", line 46, in drawChart
    drawMetricChart(data, metric, container)
  File "/home/axhu/VectorDBBench/vectordb_bench/frontend/components/check_results/charts.py", line 164, in drawMetricChart
    chart.plotly_chart(fig, use_container_width=True)
  File "/opt/anaconda3/envs/py311/lib/python3.11/site-packages/streamlit/runtime/metrics_util.py", line 410, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/py311/lib/python3.11/site-packages/streamlit/elements/plotly_chart.py", line 506, in plotly_chart
    plotly_chart_proto.id = compute_and_register_element_id(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/py311/lib/python3.11/site-packages/streamlit/elements/lib/utils.py", line 226, in compute_and_register_element_id
    _register_element_id(ctx, element_type, element_id)
  File "/opt/anaconda3/envs/py311/lib/python3.11/site-packages/streamlit/elements/lib/utils.py", line 132, in _register_element_id
    raise StreamlitDuplicateElementId(element_type)
streamlit.errors.StreamlitDuplicateElementId: There are multiple `plotly_chart` elements with the same auto-generated ID. When this element is created, it is assigned an internal ID based on the element type and provided parameters. Multiple elements with the same type and parameters will cause this error.

How can i solve this error?

user is root
step:

sh /home/axhu/init.sh

 vim init.sh

#!/bin/bash

# conda init && conda activate py311
timestamp=$(date +"%Y%m%d-%H_%M_%S")
# cd /home/xbli10/vectordbbench/
cd /home/axhu/VectorDBBench/
command="python -m vectordb_bench |& tee /home/axhu/log/result_${timestamp}.log &"
eval ${command}
cd /home/axhu

**Comment by alwayslove2013** [comment]
@midonKing Could you please check the `VectorDBBench` version?
"streamlit.errors.StreamlitDuplicateElementId" has been fixed in PR: #386 ([v0.0.14](https://github.com/zilliztech/VectorDBBench/releases/tag/v0.0.14))

**Comment by midonKing** [comment]
> @midonKing Could you please check the `VectorDBBench` version? "streamlit.errors.StreamlitDuplicateElementId" has been fixed in PR: #386 ([v0.0.14](https://github.com/zilliztech/VectorDBBench/releases/tag/v0.0.14))

yes,You are right, I upgraded the version to solve the problem, thank you!
