### ISSUE TITLE
Benchmark failing during the search 

### ISSUE THREAD

**Issue by kilo1234** [zilliztech/VectorDBBench#406]
VectordbBench keeps ending abruptly when run on weaviate:

2024-11-12 15:27:15,918 | INFO: Syncing all process and start concurrency search, concurrency=70 (mp_runner.py:109) (59439)
2024-11-12 15:27:21,699 | WARNING: VectorDB search_embedding error: 'NoneType' object is not iterable (mp_runner.py:64) (104869)
Traceback (most recent call last):
  File "/home/ubuntu/.venv/lib/python3.11/site-packages/vectordb_bench/backend/runner/mp_runner.py", line 58, in search
    self.db.search_embedding(
  File "/home/ubuntu/.venv/lib/python3.11/site-packages/vectordb_bench/backend/clients/weaviate_cloud/weaviate_cloud.py", line 141, in search_embedding
    ret = [result[self._scalar_field] for result in res["data"]["Get"][self.collection_name]]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by alwayslove2013** [comment]
@kilo1234 I will check it.
