### ISSUE TITLE
ImportError: cannot import name 'config' from 'vectordb_bench' (unknown location)

### ISSUE THREAD

**Issue by pankaj2590** [zilliztech/VectorDBBench#408]
I am trying to install and run test server. 
I installed qdrant tests using following commands:

**_pip install -e '.[test]'
pip install -e '.[qdrant]'_**  << I want to run benchmarks for qdrant-cloud

Later trying, following commands to run and getting error:
**_**(vdbenv) ubuntu@master:~/VectorDBBench$ init_bench
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/vdbenv/bin/init_bench", line 5, in <module>
    from vectordb_bench.__main__ import main
  File "/home/ubuntu/VectorDBBench/vectordb_bench/__main__.py", line 5, in <module>
    from . import config
ImportError: cannot import name 'config' from 'vectordb_bench' (unknown location)
(vdbenv) ubuntu@master:~/VectorDBBench$**_**

What could be the issue here and how can we avoid it ?

**Comment by pankaj2590** [comment]
After deleting the pyenv, working fine.
